# Generated by Django 3.1.14 on 2022-11-20 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی سازنده')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='title')),
                ('body', mdeditor.fields.MDTextField(verbose_name='text')),
                ('pub_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='release_time')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='point')),
                ('count_scorer', models.PositiveIntegerField(default=0, verbose_name='count_pointed')),
                ('article_order', models.IntegerField(default=0, verbose_name='article_order')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_article_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقاله',
                'ordering': ['-article_order', '-pub_time'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='VerificationSms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='موبایل')),
                ('code', models.CharField(max_length=10, verbose_name='کد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('update_count', models.SmallIntegerField(default=0)),
                ('lifetime', models.SmallIntegerField(default=3)),
                ('usage', models.SmallIntegerField(choices=[(1, 'Register'), (2, 'Reset Password'), (3, 'Login with sms')], default=1)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='UserMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.CharField(max_length=20, null=True, unique=True)),
                ('phone', models.CharField(max_length=11, null=True, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('gender', models.SmallIntegerField(choices=[(0, 'پسر'), (1, 'دختر'), (2, 'نامعلوم')], default=2, null=True)),
                ('type', models.IntegerField(choices=[(0, 'نامعلوم'), (1, 'دانش آموز'), (2, 'معلم')], default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ویژگی کاربر',
                'verbose_name_plural': 'ویژگی کاربران',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True, verbose_name='آی\u200cپی سازنده')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='score')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article', verbose_name='article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_point_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'امتیاز',
                'verbose_name_plural': 'امتیاز',
                'ordering': ['-id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.GenericIPAddressField(blank=True, default='', editable=False, null=True)),
                ('changed_fields', models.JSONField(default=dict, verbose_name='تغییرات')),
                ('object_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('action', models.SmallIntegerField(choices=[(0, 'add'), (1, 'edit'), (2, 'delete')], default=1, editable=False)),
                ('priority', models.SmallIntegerField(default=1)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='نوع محتوا')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فهرست تغییرات',
                'verbose_name_plural': 'فهرست تغییرات',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('body', models.JSONField(default=dict)),
                ('ctype', models.IntegerField(choices=[(1, 'SMS'), (2, 'Email')], default=1)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Inprogress'), (2, 'Retry'), (9, 'Failed'), (10, 'Done')], default=0)),
                ('target', models.CharField(max_length=50)),
                ('target_group', models.IntegerField(blank=True, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('stop_at', models.DateTimeField(blank=True, null=True)),
                ('index', models.CharField(default='', max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('gtw', models.IntegerField(choices=[(0, 'unknown gateway'), (1, 'django send mail'), (11, 'parsa sms'), (12, 'parsa template sms'), (13, 'kavenegar sms')], default=0)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
