# Generated by Django 3.1.14 on 2022-11-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221120_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': 'id', 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقاله'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_order',
        ),
    ]
